# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bank', models.IntegerField()),
                ('buy_insurance', models.IntegerField()),
                ('citizenship', models.IntegerField()),
                ('income', models.IntegerField()),
                ('insurance', models.IntegerField()),
                ('intention', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('type', models.IntegerField()),
                ('urgency', models.IntegerField()),
            ],
        ),
    ]
